// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"DemoLayout":{"id":"DemoLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/performance_optimization/index":{"path":"performance_optimization","id":"docs/performance_optimization/index","parentId":"DocLayout"},"docs/browser/web_security":{"path":"browser/web_security","id":"docs/browser/web_security","parentId":"DocLayout"},"docs/js/dom-analyseHTML":{"path":"js/dom-analysehtml","id":"docs/js/dom-analyseHTML","parentId":"DocLayout"},"docs/engineering/index":{"path":"engineering","id":"docs/engineering/index","parentId":"DocLayout"},"docs/browser/index2":{"path":"browser/index2","id":"docs/browser/index2","parentId":"DocLayout"},"docs/browser/index3":{"path":"browser/index3","id":"docs/browser/index3","parentId":"DocLayout"},"docs/browser/index":{"path":"browser","id":"docs/browser/index","parentId":"DocLayout"},"docs/js/es-closure":{"path":"js/es-closure","id":"docs/js/es-closure","parentId":"DocLayout"},"docs/network/index":{"path":"network","id":"docs/network/index","parentId":"DocLayout"},"docs/network/test":{"path":"network/test","id":"docs/network/test","parentId":"DocLayout"},"docs/js/css-flex":{"path":"js/css-flex","id":"docs/js/css-flex","parentId":"DocLayout"},"docs/js/css-1px":{"path":"js/css-1px","id":"docs/js/css-1px","parentId":"DocLayout"},"docs/js/es-this":{"path":"js/es-this","id":"docs/js/es-this","parentId":"DocLayout"},"docs/node/index":{"path":"node","id":"docs/node/index","parentId":"DocLayout"},"docs/js/index":{"path":"js","id":"docs/js/index","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"DemoLayout"}},
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/paultion/Desktop/paultion.github.io/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/paultion/Desktop/paultion.github.io/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/paultion/Desktop/paultion.github.io/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'DemoLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi-theme-mobile__dist__layouts__DemoLayout" */'/Users/paultion/Desktop/paultion.github.io/node_modules/dumi-theme-mobile/dist/layouts/DemoLayout.js')),
'docs/performance_optimization/index': React.lazy(() => import(/* webpackChunkName: "docs__performance_optimization__index.md" */'/Users/paultion/Desktop/paultion.github.io/docs/performance_optimization/index.md')),
'docs/browser/web_security': React.lazy(() => import(/* webpackChunkName: "docs__browser__web_security.md" */'/Users/paultion/Desktop/paultion.github.io/docs/browser/web_security.md')),
'docs/js/dom-analyseHTML': React.lazy(() => import(/* webpackChunkName: "docs__js__dom-analyseHTML.md" */'/Users/paultion/Desktop/paultion.github.io/docs/js/dom-analyseHTML.md')),
'docs/engineering/index': React.lazy(() => import(/* webpackChunkName: "docs__engineering__index.md" */'/Users/paultion/Desktop/paultion.github.io/docs/engineering/index.md')),
'docs/browser/index2': React.lazy(() => import(/* webpackChunkName: "docs__browser__index2.md" */'/Users/paultion/Desktop/paultion.github.io/docs/browser/index2.md')),
'docs/browser/index3': React.lazy(() => import(/* webpackChunkName: "docs__browser__index3.md" */'/Users/paultion/Desktop/paultion.github.io/docs/browser/index3.md')),
'docs/browser/index': React.lazy(() => import(/* webpackChunkName: "docs__browser__index.md" */'/Users/paultion/Desktop/paultion.github.io/docs/browser/index.md')),
'docs/js/es-closure': React.lazy(() => import(/* webpackChunkName: "docs__js__es-closure.md" */'/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.md')),
'docs/network/index': React.lazy(() => import(/* webpackChunkName: "docs__network__index.md" */'/Users/paultion/Desktop/paultion.github.io/docs/network/index.md')),
'docs/network/test': React.lazy(() => import(/* webpackChunkName: "docs__network__test.md" */'/Users/paultion/Desktop/paultion.github.io/docs/network/test.md')),
'docs/js/css-flex': React.lazy(() => import(/* webpackChunkName: "docs__js__css-flex.md" */'/Users/paultion/Desktop/paultion.github.io/docs/js/css-flex.md')),
'docs/js/css-1px': React.lazy(() => import(/* webpackChunkName: "docs__js__css-1px.md" */'/Users/paultion/Desktop/paultion.github.io/docs/js/css-1px.md')),
'docs/js/es-this': React.lazy(() => import(/* webpackChunkName: "docs__js__es-this.md" */'/Users/paultion/Desktop/paultion.github.io/docs/js/es-this.md')),
'docs/node/index': React.lazy(() => import(/* webpackChunkName: "docs__node__index.md" */'/Users/paultion/Desktop/paultion.github.io/docs/node/index.md')),
'docs/js/index': React.lazy(() => import(/* webpackChunkName: "docs__js__index.md" */'/Users/paultion/Desktop/paultion.github.io/docs/js/index.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/paultion/Desktop/paultion.github.io/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/paultion/Desktop/paultion.github.io/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
