// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"DemoLayout":{"id":"DemoLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/browser/web_security":{"path":"browser/web_security","id":"docs/browser/web_security","parentId":"DocLayout"},"docs/browser/index":{"path":"browser","id":"docs/browser/index","parentId":"DocLayout"},"docs/network/index":{"path":"network","id":"docs/network/index","parentId":"DocLayout"},"docs/js/css/index":{"path":"js/css","id":"docs/js/css/index","parentId":"DocLayout"},"docs/network/test":{"path":"network/test","id":"docs/network/test","parentId":"DocLayout"},"docs/js/css/flex":{"path":"js/css/flex","id":"docs/js/css/flex","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"DemoLayout"}},
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/paultion/Desktop/paultion.github.io/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'/Users/paultion/Desktop/paultion.github.io/.dumi/tmp-production/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/paultion/Desktop/paultion.github.io/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'DemoLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi-theme-mobile__dist__layouts__DemoLayout" */'/Users/paultion/Desktop/paultion.github.io/node_modules/dumi-theme-mobile/dist/layouts/DemoLayout.js')),
'docs/browser/web_security': React.lazy(() => import(/* webpackChunkName: "docs__browser__web_security.md" */'/Users/paultion/Desktop/paultion.github.io/docs/browser/web_security.md')),
'docs/browser/index': React.lazy(() => import(/* webpackChunkName: "docs__browser__index.md" */'/Users/paultion/Desktop/paultion.github.io/docs/browser/index.md')),
'docs/network/index': React.lazy(() => import(/* webpackChunkName: "docs__network__index.md" */'/Users/paultion/Desktop/paultion.github.io/docs/network/index.md')),
'docs/js/css/index': React.lazy(() => import(/* webpackChunkName: "docs__js__css__index.md" */'/Users/paultion/Desktop/paultion.github.io/docs/js/css/index.md')),
'docs/network/test': React.lazy(() => import(/* webpackChunkName: "docs__network__test.md" */'/Users/paultion/Desktop/paultion.github.io/docs/network/test.md')),
'docs/js/css/flex': React.lazy(() => import(/* webpackChunkName: "docs__js__css__flex.md" */'/Users/paultion/Desktop/paultion.github.io/docs/js/css/flex.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/paultion/Desktop/paultion.github.io/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/paultion/Desktop/paultion.github.io/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
