// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demos as dm0, frontmatter as fm0, toc as toc0, texts as txt0 } from '/Users/paultion/Desktop/paultion.github.io/docs/performance_optimization/index.md?type=meta';
import { demos as dm1, frontmatter as fm1, toc as toc1, texts as txt1 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/same_origin_policy.md?type=meta';
import { demos as dm2, frontmatter as fm2, toc as toc2, texts as txt2 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/rendering_process.md?type=meta';
import { demos as dm3, frontmatter as fm3, toc as toc3, texts as txt3 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/caching_strategy.md?type=meta';
import { demos as dm4, frontmatter as fm4, toc as toc4, texts as txt4 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/web_security.md?type=meta';
import { demos as dm5, frontmatter as fm5, toc as toc5, texts as txt5 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-design_pattern.md?type=meta';
import { demos as dm6, frontmatter as fm6, toc as toc6, texts as txt6 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/dom-analyseHTML.md?type=meta';
import { demos as dm7, frontmatter as fm7, toc as toc7, texts as txt7 } from '/Users/paultion/Desktop/paultion.github.io/docs/engineering/index.md?type=meta';
import { demos as dm8, frontmatter as fm8, toc as toc8, texts as txt8 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-eventloop.md?type=meta';
import { demos as dm9, frontmatter as fm9, toc as toc9, texts as txt9 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-prototype.md?type=meta';
import { demos as dm10, frontmatter as fm10, toc as toc10, texts as txt10 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/index.md?type=meta';
import { demos as dm11, frontmatter as fm11, toc as toc11, texts as txt11 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.md?type=meta';
import { demos as dm12, frontmatter as fm12, toc as toc12, texts as txt12 } from '/Users/paultion/Desktop/paultion.github.io/docs/network/index.md?type=meta';
import { demos as dm13, frontmatter as fm13, toc as toc13, texts as txt13 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-extend.md?type=meta';
import { demos as dm14, frontmatter as fm14, toc as toc14, texts as txt14 } from '/Users/paultion/Desktop/paultion.github.io/docs/network/test.md?type=meta';
import { demos as dm15, frontmatter as fm15, toc as toc15, texts as txt15 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/css-flex.md?type=meta';
import { demos as dm16, frontmatter as fm16, toc as toc16, texts as txt16 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/css-1px.md?type=meta';
import { demos as dm17, frontmatter as fm17, toc as toc17, texts as txt17 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-this.md?type=meta';
import { demos as dm18, frontmatter as fm18, toc as toc18, texts as txt18 } from '/Users/paultion/Desktop/paultion.github.io/docs/node/index.md?type=meta';
import { demos as dm19, frontmatter as fm19, toc as toc19, texts as txt19 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-gc.md?type=meta';
import { demos as dm20, frontmatter as fm20, toc as toc20, texts as txt20 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/index.md?type=meta';
import { demos as dm21, frontmatter as fm21, toc as toc21, texts as txt21 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/css.md?type=meta';
import { demos as dm22, frontmatter as fm22, toc as toc22, texts as txt22 } from '/Users/paultion/Desktop/paultion.github.io/docs/index.md?type=meta';
import { demos as dm23, frontmatter as fm23, toc as toc23, texts as txt23 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.$tab-debounce-throttle-example.md?type=meta';
import { demos as dm24, frontmatter as fm24, toc as toc24, texts as txt24 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-extend.$tab-parasitic_combination.md?type=meta';
import { demos as dm25, frontmatter as fm25, toc as toc25, texts as txt25 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.$tab-debounce-throttle.md?type=meta';
import { demos as dm26, frontmatter as fm26, toc as toc26, texts as txt26 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.$tab-functional.md?type=meta';
import { demos as dm27, frontmatter as fm27, toc as toc27, texts as txt27 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-eventloop.$tab-promise.md?type=meta';
import { demos as dm28, frontmatter as fm28, toc as toc28, texts as txt28 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/css-flex.$tab-example.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/performance_optimization/index': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/browser/same_origin_policy': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/browser/rendering_process': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/browser/caching_strategy': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/browser/web_security': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/js/es-design_pattern': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/js/dom-analyseHTML': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/engineering/index': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/js/es-eventloop': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
    tabs: ["docs/js/es-eventloop.$tab-promise"],
  },
  'docs/js/es-prototype': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'docs/browser/index': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'docs/js/es-closure': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
    tabs: ["docs/js/es-closure.$tab-debounce-throttle-example","docs/js/es-closure.$tab-debounce-throttle","docs/js/es-closure.$tab-functional"],
  },
  'docs/network/index': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'docs/js/es-extend': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
    tabs: ["docs/js/es-extend.$tab-parasitic_combination"],
  },
  'docs/network/test': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'docs/js/css-flex': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
    tabs: ["docs/js/css-flex.$tab-example"],
  },
  'docs/js/css-1px': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'docs/js/es-this': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'docs/node/index': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'docs/js/es-gc': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'docs/js/index': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'docs/js/css': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'docs/index': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'docs/js/es-closure.$tab-debounce-throttle-example': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'docs/js/es-extend.$tab-parasitic_combination': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'docs/js/es-closure.$tab-debounce-throttle': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'docs/js/es-closure.$tab-functional': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'docs/js/es-eventloop.$tab-promise': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  'docs/js/css-flex.$tab-example': {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
  },
}

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
