// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demos as dm0, frontmatter as fm0, toc as toc0, texts as txt0 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks-custom-use_event_emitter.md?type=meta';
import { demos as dm1, frontmatter as fm1, toc as toc1, texts as txt1 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/archiitecture-concurrent_mode.md?type=meta';
import { demos as dm2, frontmatter as fm2, toc as toc2, texts as txt2 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/browser-same_origin_policy.md?type=meta';
import { demos as dm3, frontmatter as fm3, toc as toc3, texts as txt3 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks-custom-use_virtualized.md?type=meta';
import { demos as dm4, frontmatter as fm4, toc as toc4, texts as txt4 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/browser-rendering_process.md?type=meta';
import { demos as dm5, frontmatter as fm5, toc as toc5, texts as txt5 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/network-osi_network_model.md?type=meta';
import { demos as dm6, frontmatter as fm6, toc as toc6, texts as txt6 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/browser-caching_strategy.md?type=meta';
import { demos as dm7, frontmatter as fm7, toc as toc7, texts as txt7 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks-custom-use_previous.md?type=meta';
import { demos as dm8, frontmatter as fm8, toc as toc8, texts as txt8 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks-custom-use_reactive.md?type=meta';
import { demos as dm9, frontmatter as fm9, toc as toc9, texts as txt9 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/browser-web_security.md?type=meta';
import { demos as dm10, frontmatter as fm10, toc as toc10, texts as txt10 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/network-status_code.md?type=meta';
import { demos as dm11, frontmatter as fm11, toc as toc11, texts as txt11 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/RegExp-parse_thousands.md?type=meta';
import { demos as dm12, frontmatter as fm12, toc as toc12, texts as txt12 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/optimize-useVirtualized.md?type=meta';
import { demos as dm13, frontmatter as fm13, toc as toc13, texts as txt13 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/archiitecture-fiber.md?type=meta';
import { demos as dm14, frontmatter as fm14, toc as toc14, texts as txt14 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/network-protocol.md?type=meta';
import { demos as dm15, frontmatter as fm15, toc as toc15, texts as txt15 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/RegExp-longest_char.md?type=meta';
import { demos as dm16, frontmatter as fm16, toc as toc16, texts as txt16 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/architecture-v16+.md?type=meta';
import { demos as dm17, frontmatter as fm17, toc as toc17, texts as txt17 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/architecture-v15.md?type=meta';
import { demos as dm18, frontmatter as fm18, toc as toc18, texts as txt18 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-parse_DOM_tree.md?type=meta';
import { demos as dm19, frontmatter as fm19, toc as toc19, texts as txt19 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks-useEffect.md?type=meta';
import { demos as dm20, frontmatter as fm20, toc as toc20, texts as txt20 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-design_pattern.md?type=meta';
import { demos as dm21, frontmatter as fm21, toc as toc21, texts as txt21 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/babel-polyfill.md?type=meta';
import { demos as dm22, frontmatter as fm22, toc as toc22, texts as txt22 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks-useState.md?type=meta';
import { demos as dm23, frontmatter as fm23, toc as toc23, texts as txt23 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/suspense/index.md?type=meta';
import { demos as dm24, frontmatter as fm24, toc as toc24, texts as txt24 } from '/Users/paultion/Desktop/paultion.github.io/docs/webpack/optimization.md?type=meta';
import { demos as dm25, frontmatter as fm25, toc as toc25, texts as txt25 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/context/index.md?type=meta';
import { demos as dm26, frontmatter as fm26, toc as toc26, texts as txt26 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-max_version.md?type=meta';
import { demos as dm27, frontmatter as fm27, toc as toc27, texts as txt27 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-parentheses.md?type=meta';
import { demos as dm28, frontmatter as fm28, toc as toc28, texts as txt28 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-parse_camel.md?type=meta';
import { demos as dm29, frontmatter as fm29, toc as toc29, texts as txt29 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/dom-analyseHTML.md?type=meta';
import { demos as dm30, frontmatter as fm30, toc as toc30, texts as txt30 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks/index.md?type=meta';
import { demos as dm31, frontmatter as fm31, toc as toc31, texts as txt31 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-deep_copy.md?type=meta';
import { demos as dm32, frontmatter as fm32, toc as toc32, texts as txt32 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-eventloop.md?type=meta';
import { demos as dm33, frontmatter as fm33, toc as toc33, texts as txt33 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-fibonacci.md?type=meta';
import { demos as dm34, frontmatter as fm34, toc as toc34, texts as txt34 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks-deps.md?type=meta';
import { demos as dm35, frontmatter as fm35, toc as toc35, texts as txt35 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-eventloop.md?type=meta';
import { demos as dm36, frontmatter as fm36, toc as toc36, texts as txt36 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-prototype.md?type=meta';
import { demos as dm37, frontmatter as fm37, toc as toc37, texts as txt37 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-flatten.md?type=meta';
import { demos as dm38, frontmatter as fm38, toc as toc38, texts as txt38 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/setState.md?type=meta';
import { demos as dm39, frontmatter as fm39, toc as toc39, texts as txt39 } from '/Users/paultion/Desktop/paultion.github.io/docs/webpack/plugin.md?type=meta';
import { demos as dm40, frontmatter as fm40, toc as toc40, texts as txt40 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/index.md?type=meta';
import { demos as dm41, frontmatter as fm41, toc as toc41, texts as txt41 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.md?type=meta';
import { demos as dm42, frontmatter as fm42, toc as toc42, texts as txt42 } from '/Users/paultion/Desktop/paultion.github.io/docs/webpack/index.md?type=meta';
import { demos as dm43, frontmatter as fm43, toc as toc43, texts as txt43 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-extend.md?type=meta';
import { demos as dm44, frontmatter as fm44, toc as toc44, texts as txt44 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/router.md?type=meta';
import { demos as dm45, frontmatter as fm45, toc as toc45, texts as txt45 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/css-flex.md?type=meta';
import { demos as dm46, frontmatter as fm46, toc as toc46, texts as txt46 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/index.md?type=meta';
import { demos as dm47, frontmatter as fm47, toc as toc47, texts as txt47 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/redux.md?type=meta';
import { demos as dm48, frontmatter as fm48, toc as toc48, texts as txt48 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/css-1px.md?type=meta';
import { demos as dm49, frontmatter as fm49, toc as toc49, texts as txt49 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-this.md?type=meta';
import { demos as dm50, frontmatter as fm50, toc as toc50, texts as txt50 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/diff.md?type=meta';
import { demos as dm51, frontmatter as fm51, toc as toc51, texts as txt51 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/index.md?type=meta';
import { demos as dm52, frontmatter as fm52, toc as toc52, texts as txt52 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/module.md?type=meta';
import { demos as dm53, frontmatter as fm53, toc as toc53, texts as txt53 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-gc.md?type=meta';
import { demos as dm54, frontmatter as fm54, toc as toc54, texts as txt54 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/index.md?type=meta';
import { demos as dm55, frontmatter as fm55, toc as toc55, texts as txt55 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/css.md?type=meta';
import { demos as dm56, frontmatter as fm56, toc as toc56, texts as txt56 } from '/Users/paultion/Desktop/paultion.github.io/docs/index.md?type=meta';
import { demos as dm57, frontmatter as fm57, toc as toc57, texts as txt57 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/ts.md?type=meta';
import { demos as dm58, frontmatter as fm58, toc as toc58, texts as txt58 } from '/Users/paultion/Desktop/paultion.github.io/src/index.md?type=meta';
import { demos as dm59, frontmatter as fm59, toc as toc59, texts as txt59 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-eventloop.$tab-promise-all-race-resolve-reject-allSettled.md?type=meta';
import { demos as dm60, frontmatter as fm60, toc as toc60, texts as txt60 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks/index.$tab-use_use_sync_external_store.md?type=meta';
import { demos as dm61, frontmatter as fm61, toc as toc61, texts as txt61 } from '/Users/paultion/Desktop/paultion.github.io/docs/webpack/plugin.$tab-css_treeshakingwebpack_plugin.md?type=meta';
import { demos as dm62, frontmatter as fm62, toc as toc62, texts as txt62 } from '/Users/paultion/Desktop/paultion.github.io/docs/webpack/plugin.$tab-auto_routes_define_plugin.md?type=meta';
import { demos as dm63, frontmatter as fm63, toc as toc63, texts as txt63 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.$tab-debounce-throttle-example.md?type=meta';
import { demos as dm64, frontmatter as fm64, toc as toc64, texts as txt64 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-eventloop.$tab-promise-catch-finally.md?type=meta';
import { demos as dm65, frontmatter as fm65, toc as toc65, texts as txt65 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-eventloop.$tab-concurrence_control.md?type=meta';
import { demos as dm66, frontmatter as fm66, toc as toc66, texts as txt66 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks/index.$tab-use_deferred_value.md?type=meta';
import { demos as dm67, frontmatter as fm67, toc as toc67, texts as txt67 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-extend.$tab-parasitic_combination.md?type=meta';
import { demos as dm68, frontmatter as fm68, toc as toc68, texts as txt68 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-parse_camel.$tab-parse_2_camel.md?type=meta';
import { demos as dm69, frontmatter as fm69, toc as toc69, texts as txt69 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks/index.$tab-use_transition.md?type=meta';
import { demos as dm70, frontmatter as fm70, toc as toc70, texts as txt70 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.$tab-debounce-throttle.md?type=meta';
import { demos as dm71, frontmatter as fm71, toc as toc71, texts as txt71 } from '/Users/paultion/Desktop/paultion.github.io/docs/browser/network-protocol.$tab-http.md?type=meta';
import { demos as dm72, frontmatter as fm72, toc as toc72, texts as txt72 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-eventloop.$tab-generator.md?type=meta';
import { demos as dm73, frontmatter as fm73, toc as toc73, texts as txt73 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-prototype.$tab-instanceof.md?type=meta';
import { demos as dm74, frontmatter as fm74, toc as toc74, texts as txt74 } from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-eventloop.$tab-lazy_man.md?type=meta';
import { demos as dm75, frontmatter as fm75, toc as toc75, texts as txt75 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.$tab-functional.md?type=meta';
import { demos as dm76, frontmatter as fm76, toc as toc76, texts as txt76 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-eventloop.$tab-promise.md?type=meta';
import { demos as dm77, frontmatter as fm77, toc as toc77, texts as txt77 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/diff.$tab-reconcile.md?type=meta';
import { demos as dm78, frontmatter as fm78, toc as toc78, texts as txt78 } from '/Users/paultion/Desktop/paultion.github.io/docs/js/css-flex.$tab-example.md?type=meta';
import { demos as dm79, frontmatter as fm79, toc as toc79, texts as txt79 } from '/Users/paultion/Desktop/paultion.github.io/docs/react/diff.$tab-key.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/react/hooks-custom-use_event_emitter': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/react/archiitecture-concurrent_mode': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/browser/browser-same_origin_policy': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/react/hooks-custom-use_virtualized': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/browser/browser-rendering_process': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/browser/network-osi_network_model': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/browser/browser-caching_strategy': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/react/hooks-custom-use_previous': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/react/hooks-custom-use_reactive': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'docs/browser/browser-web_security': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'docs/browser/network-status_code': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'docs/FAQ/RegExp-parse_thousands': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'docs/js/optimize-useVirtualized': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'docs/react/archiitecture-fiber': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'docs/browser/network-protocol': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
    tabs: ["docs/browser/network-protocol.$tab-http"],
  },
  'docs/FAQ/RegExp-longest_char': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'docs/react/architecture-v16+': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'docs/react/architecture-v15': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'docs/FAQ/es-parse_DOM_tree': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'docs/react/hooks-useEffect': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'docs/js/es-design_pattern': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'docs/react/babel-polyfill': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'docs/react/hooks-useState': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'docs/react/suspense/index': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'docs/webpack/optimization': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'docs/react/context/index': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'docs/FAQ/es-max_version': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'docs/FAQ/es-parentheses': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  'docs/FAQ/es-parse_camel': {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
    tabs: ["docs/FAQ/es-parse_camel.$tab-parse_2_camel"],
  },
  'docs/js/dom-analyseHTML': {
    frontmatter: fm29,
    toc: toc29,
    texts: txt29,
    demos: dm29,
  },
  'docs/react/hooks/index': {
    frontmatter: fm30,
    toc: toc30,
    texts: txt30,
    demos: dm30,
    tabs: ["docs/react/hooks/index.$tab-use_use_sync_external_store","docs/react/hooks/index.$tab-use_deferred_value","docs/react/hooks/index.$tab-use_transition","docs/react/hooks/index.$tab-use_todo_list"],
  },
  'docs/FAQ/es-deep_copy': {
    frontmatter: fm31,
    toc: toc31,
    texts: txt31,
    demos: dm31,
  },
  'docs/FAQ/es-eventloop': {
    frontmatter: fm32,
    toc: toc32,
    texts: txt32,
    demos: dm32,
    tabs: ["docs/FAQ/es-eventloop.$tab-concurrence_control","docs/FAQ/es-eventloop.$tab-generator","docs/FAQ/es-eventloop.$tab-lazy_man"],
  },
  'docs/FAQ/es-fibonacci': {
    frontmatter: fm33,
    toc: toc33,
    texts: txt33,
    demos: dm33,
  },
  'docs/react/hooks-deps': {
    frontmatter: fm34,
    toc: toc34,
    texts: txt34,
    demos: dm34,
  },
  'docs/js/es-eventloop': {
    frontmatter: fm35,
    toc: toc35,
    texts: txt35,
    demos: dm35,
    tabs: ["docs/js/es-eventloop.$tab-promise-all-race-resolve-reject-allSettled","docs/js/es-eventloop.$tab-promise-catch-finally","docs/js/es-eventloop.$tab-promise"],
  },
  'docs/js/es-prototype': {
    frontmatter: fm36,
    toc: toc36,
    texts: txt36,
    demos: dm36,
    tabs: ["docs/js/es-prototype.$tab-instanceof"],
  },
  'docs/FAQ/es-flatten': {
    frontmatter: fm37,
    toc: toc37,
    texts: txt37,
    demos: dm37,
  },
  'docs/react/setState': {
    frontmatter: fm38,
    toc: toc38,
    texts: txt38,
    demos: dm38,
  },
  'docs/webpack/plugin': {
    frontmatter: fm39,
    toc: toc39,
    texts: txt39,
    demos: dm39,
    tabs: ["docs/webpack/plugin.$tab-css_treeshakingwebpack_plugin","docs/webpack/plugin.$tab-auto_routes_define_plugin"],
  },
  'docs/browser/index': {
    frontmatter: fm40,
    toc: toc40,
    texts: txt40,
    demos: dm40,
  },
  'docs/js/es-closure': {
    frontmatter: fm41,
    toc: toc41,
    texts: txt41,
    demos: dm41,
    tabs: ["docs/js/es-closure.$tab-debounce-throttle-example","docs/js/es-closure.$tab-debounce-throttle","docs/js/es-closure.$tab-functional"],
  },
  'docs/webpack/index': {
    frontmatter: fm42,
    toc: toc42,
    texts: txt42,
    demos: dm42,
  },
  'docs/js/es-extend': {
    frontmatter: fm43,
    toc: toc43,
    texts: txt43,
    demos: dm43,
    tabs: ["docs/js/es-extend.$tab-parasitic_combination"],
  },
  'docs/react/router': {
    frontmatter: fm44,
    toc: toc44,
    texts: txt44,
    demos: dm44,
  },
  'docs/js/css-flex': {
    frontmatter: fm45,
    toc: toc45,
    texts: txt45,
    demos: dm45,
    tabs: ["docs/js/css-flex.$tab-example"],
  },
  'docs/react/index': {
    frontmatter: fm46,
    toc: toc46,
    texts: txt46,
    demos: dm46,
  },
  'docs/react/redux': {
    frontmatter: fm47,
    toc: toc47,
    texts: txt47,
    demos: dm47,
  },
  'docs/js/css-1px': {
    frontmatter: fm48,
    toc: toc48,
    texts: txt48,
    demos: dm48,
  },
  'docs/js/es-this': {
    frontmatter: fm49,
    toc: toc49,
    texts: txt49,
    demos: dm49,
  },
  'docs/react/diff': {
    frontmatter: fm50,
    toc: toc50,
    texts: txt50,
    demos: dm50,
    tabs: ["docs/react/diff.$tab-reconcile","docs/react/diff.$tab-key"],
  },
  'docs/FAQ/index': {
    frontmatter: fm51,
    toc: toc51,
    texts: txt51,
    demos: dm51,
  },
  'docs/js/module': {
    frontmatter: fm52,
    toc: toc52,
    texts: txt52,
    demos: dm52,
  },
  'docs/js/es-gc': {
    frontmatter: fm53,
    toc: toc53,
    texts: txt53,
    demos: dm53,
  },
  'docs/js/index': {
    frontmatter: fm54,
    toc: toc54,
    texts: txt54,
    demos: dm54,
  },
  'docs/js/css': {
    frontmatter: fm55,
    toc: toc55,
    texts: txt55,
    demos: dm55,
  },
  'docs/index': {
    frontmatter: fm56,
    toc: toc56,
    texts: txt56,
    demos: dm56,
  },
  'docs/js/ts': {
    frontmatter: fm57,
    toc: toc57,
    texts: txt57,
    demos: dm57,
  },
  'apis/index': {
    frontmatter: fm58,
    toc: toc58,
    texts: txt58,
    demos: dm58,
  },
  'docs/js/es-eventloop.$tab-promise-all-race-resolve-reject-allSettled': {
    frontmatter: fm59,
    toc: toc59,
    texts: txt59,
    demos: dm59,
  },
  'docs/react/hooks/index.$tab-use_use_sync_external_store': {
    frontmatter: fm60,
    toc: toc60,
    texts: txt60,
    demos: dm60,
  },
  'docs/webpack/plugin.$tab-css_treeshakingwebpack_plugin': {
    frontmatter: fm61,
    toc: toc61,
    texts: txt61,
    demos: dm61,
  },
  'docs/webpack/plugin.$tab-auto_routes_define_plugin': {
    frontmatter: fm62,
    toc: toc62,
    texts: txt62,
    demos: dm62,
  },
  'docs/js/es-closure.$tab-debounce-throttle-example': {
    frontmatter: fm63,
    toc: toc63,
    texts: txt63,
    demos: dm63,
  },
  'docs/js/es-eventloop.$tab-promise-catch-finally': {
    frontmatter: fm64,
    toc: toc64,
    texts: txt64,
    demos: dm64,
  },
  'docs/FAQ/es-eventloop.$tab-concurrence_control': {
    frontmatter: fm65,
    toc: toc65,
    texts: txt65,
    demos: dm65,
  },
  'docs/react/hooks/index.$tab-use_deferred_value': {
    frontmatter: fm66,
    toc: toc66,
    texts: txt66,
    demos: dm66,
  },
  'docs/js/es-extend.$tab-parasitic_combination': {
    frontmatter: fm67,
    toc: toc67,
    texts: txt67,
    demos: dm67,
  },
  'docs/FAQ/es-parse_camel.$tab-parse_2_camel': {
    frontmatter: fm68,
    toc: toc68,
    texts: txt68,
    demos: dm68,
  },
  'docs/react/hooks/index.$tab-use_transition': {
    frontmatter: fm69,
    toc: toc69,
    texts: txt69,
    demos: dm69,
  },
  'docs/js/es-closure.$tab-debounce-throttle': {
    frontmatter: fm70,
    toc: toc70,
    texts: txt70,
    demos: dm70,
  },
  'docs/browser/network-protocol.$tab-http': {
    frontmatter: fm71,
    toc: toc71,
    texts: txt71,
    demos: dm71,
  },
  'docs/FAQ/es-eventloop.$tab-generator': {
    frontmatter: fm72,
    toc: toc72,
    texts: txt72,
    demos: dm72,
  },
  'docs/js/es-prototype.$tab-instanceof': {
    frontmatter: fm73,
    toc: toc73,
    texts: txt73,
    demos: dm73,
  },
  'docs/FAQ/es-eventloop.$tab-lazy_man': {
    frontmatter: fm74,
    toc: toc74,
    texts: txt74,
    demos: dm74,
  },
  'docs/js/es-closure.$tab-functional': {
    frontmatter: fm75,
    toc: toc75,
    texts: txt75,
    demos: dm75,
  },
  'docs/js/es-eventloop.$tab-promise': {
    frontmatter: fm76,
    toc: toc76,
    texts: txt76,
    demos: dm76,
  },
  'docs/react/diff.$tab-reconcile': {
    frontmatter: fm77,
    toc: toc77,
    texts: txt77,
    demos: dm77,
  },
  'docs/js/css-flex.$tab-example': {
    frontmatter: fm78,
    toc: toc78,
    texts: txt78,
    demos: dm78,
  },
  'docs/react/diff.$tab-key': {
    frontmatter: fm79,
    toc: toc79,
    texts: txt79,
    demos: dm79,
  },
}

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
