// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import * as tab0 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.$tab-debounce-throttle-example.md';
import * as tab1 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-extend.$tab-parasitic_combination.md';
import * as tab2 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.$tab-debounce-throttle.md';
import * as tab3 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.$tab-functional.md';
import * as tab4 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-eventloop.$tab-promise.md';
import * as tab5 from '/Users/paultion/Desktop/paultion.github.io/docs/js/css-flex.$tab-example.md';

export const tabs = {
  'docs/js/es-closure.$tab-debounce-throttle-example': { key: 'debounce-throttle-example', components: tab0 },
  'docs/js/es-extend.$tab-parasitic_combination': { key: 'parasitic_combination', components: tab1 },
  'docs/js/es-closure.$tab-debounce-throttle': { key: 'debounce-throttle', components: tab2 },
  'docs/js/es-closure.$tab-functional': { key: 'functional', components: tab3 },
  'docs/js/es-eventloop.$tab-promise': { key: 'promise', components: tab4 },
  'docs/js/css-flex.$tab-example': { key: 'example', components: tab5 },
}
