// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import * as tab0 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-eventloop.$tab-promise-all-race-resolve-reject-allSettled.md';
import * as tab1 from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks/index.$tab-use_use_sync_external_store.md';
import * as tab2 from '/Users/paultion/Desktop/paultion.github.io/docs/webpack/plugin.$tab-css_treeshakingwebpack_plugin.md';
import * as tab3 from '/Users/paultion/Desktop/paultion.github.io/docs/webpack/plugin.$tab-auto_routes_define_plugin.md';
import * as tab4 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.$tab-debounce-throttle-example.md';
import * as tab5 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-eventloop.$tab-promise-catch-finally.md';
import * as tab6 from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-eventloop.$tab-concurrence_control.md';
import * as tab7 from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks/index.$tab-use_deferred_value.md';
import * as tab8 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-extend.$tab-parasitic_combination.md';
import * as tab9 from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-parse_camel.$tab-parse_2_camel.md';
import * as tab10 from '/Users/paultion/Desktop/paultion.github.io/docs/react/hooks/index.$tab-use_transition.md';
import * as tab11 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.$tab-debounce-throttle.md';
import * as tab12 from '/Users/paultion/Desktop/paultion.github.io/docs/browser/network-protocol.$tab-http.md';
import * as tab13 from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-eventloop.$tab-generator.md';
import * as tab14 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-prototype.$tab-instanceof.md';
import * as tab15 from '/Users/paultion/Desktop/paultion.github.io/docs/FAQ/es-eventloop.$tab-lazy_man.md';
import * as tab16 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-closure.$tab-functional.md';
import * as tab17 from '/Users/paultion/Desktop/paultion.github.io/docs/js/es-eventloop.$tab-promise.md';
import * as tab18 from '/Users/paultion/Desktop/paultion.github.io/docs/react/diff.$tab-reconcile.md';
import * as tab19 from '/Users/paultion/Desktop/paultion.github.io/docs/js/css-flex.$tab-example.md';
import * as tab20 from '/Users/paultion/Desktop/paultion.github.io/docs/react/diff.$tab-key.md';

export const tabs = {
  'docs/js/es-eventloop.$tab-promise-all-race-resolve-reject-allSettled': { key: 'promise-all-race-resolve-reject-allSettled', components: tab0 },
  'docs/react/hooks/index.$tab-use_use_sync_external_store': { key: 'use_use_sync_external_store', components: tab1 },
  'docs/webpack/plugin.$tab-css_treeshakingwebpack_plugin': { key: 'css_treeshakingwebpack_plugin', components: tab2 },
  'docs/webpack/plugin.$tab-auto_routes_define_plugin': { key: 'auto_routes_define_plugin', components: tab3 },
  'docs/js/es-closure.$tab-debounce-throttle-example': { key: 'debounce-throttle-example', components: tab4 },
  'docs/js/es-eventloop.$tab-promise-catch-finally': { key: 'promise-catch-finally', components: tab5 },
  'docs/FAQ/es-eventloop.$tab-concurrence_control': { key: 'concurrence_control', components: tab6 },
  'docs/react/hooks/index.$tab-use_deferred_value': { key: 'use_deferred_value', components: tab7 },
  'docs/js/es-extend.$tab-parasitic_combination': { key: 'parasitic_combination', components: tab8 },
  'docs/FAQ/es-parse_camel.$tab-parse_2_camel': { key: 'parse_2_camel', components: tab9 },
  'docs/react/hooks/index.$tab-use_transition': { key: 'use_transition', components: tab10 },
  'docs/js/es-closure.$tab-debounce-throttle': { key: 'debounce-throttle', components: tab11 },
  'docs/browser/network-protocol.$tab-http': { key: 'http', components: tab12 },
  'docs/FAQ/es-eventloop.$tab-generator': { key: 'generator', components: tab13 },
  'docs/js/es-prototype.$tab-instanceof': { key: 'instanceof', components: tab14 },
  'docs/FAQ/es-eventloop.$tab-lazy_man': { key: 'lazy_man', components: tab15 },
  'docs/js/es-closure.$tab-functional': { key: 'functional', components: tab16 },
  'docs/js/es-eventloop.$tab-promise': { key: 'promise', components: tab17 },
  'docs/react/diff.$tab-reconcile': { key: 'reconcile', components: tab18 },
  'docs/js/css-flex.$tab-example': { key: 'example', components: tab19 },
  'docs/react/diff.$tab-key': { key: 'key', components: tab20 },
}
