// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { SiteContext } from '/Users/paultion/Desktop/paultion.github.io/node_modules/dumi/dist/client/theme-api/context.js';
import { demos, components } from '../meta';
import { locales } from '../locales/config';

const entryExports = {
  
  
};

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(true);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // mark loading when route change, page component will set false when loaded
        setLoading(true);

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider value={{
      pkg: {},
      entryExports,
      demos,
      components,
      locales,
      loading,
      setLoading,
      themeConfig: {"footer":"Copyright © 2023 | Powered by <a href=\"https://d.umijs.org\" target=\"_blank\" rel=\"noreferrer\">dumi</a>","title":"","description":"描述","favicons":"/logo.png","moreLinks":[{"text":"Dumi","link":"https://d.umijs.org/"},{"text":"Ant Design","link":"https://ant.design/"}],"actions":[{"type":"primary","text":"开始使用","link":"/guide/introduce"}],"features":[{"title":"开箱即用"},{"details":"接入简单，安装即使用，全面融入 Ant Design 5.0 风格。"}]},
    }}>
      {outlet}
    </SiteContext.Provider>
  );
}
